# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.vm.define :serv1 do |serv1|
    serv1.vm.box = "ubuntu/bionic64"
    serv1.vm.network :private_network, ip: "172.42.42.101"
    serv1.vm.hostname = "serv1"
    serv1.vm.provider "virtualbox" do |v|
     v.name = "serv1"
     v.memory = 1024
     v.cpus =1
    end
  end

  config.vm.define :serv2 do |serv2|
    serv2.vm.box = "ubuntu/bionic64"
    serv2.vm.network :private_network, ip: "172.42.42.102"
    serv2.vm.hostname = "serv2"
    serv2.vm.provider "virtualbox" do |v1|
     v1.name = "serv2"
     v1.memory = 1024
     v1.cpus =1
    end
  end

  config.vm.define :serv3 do |serv3|
    serv3.vm.box = "ubuntu/bionic64"
    serv3.vm.network :private_network, ip: "172.42.42.103"
    serv3.vm.hostname = "serv3"
    serv3.vm.provider "virtualbox" do |v2|
     v2.name = "serv3"
     v2.memory = 1024
     v2.cpus =1
    end
  end

end
